# numpy

In [115]:
#1)

import numpy as np
a=np.full([5,5],0)

#a1=np.zeros([5,5], dtype=int) alternative process
print(a)

#print(a1)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [116]:
#2)
r=np.arange(10,101,5)
print(r)

[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]


In [21]:
#3)
b=np.array([[10,20,30,40,50,60]]).reshape(2,3)

In [34]:
b  #define array

array([[10, 20, 30],
       [40, 50, 60]])

In [23]:
np.shape(b)

(2, 3)

In [31]:
#3) a)
L=np.size(b)
print("the number of elements in array ::",L)

the number of elements in array :: 6


In [35]:
#3) b)
print(type(b))

<class 'numpy.ndarray'>


In [71]:
#4)

a1=np.array([1,2,3])
a2=np.array([4,5,6])

#a) addition
add=np.add(a1,a2)
print(add)

#b) subtraction
sub=np.subtract(a1,a2)
print(sub)

#c) multiplication
mul=np.multiply(a1,a2)
print(mul)

#d) division
div=np.divide(a1,a2)
print(div)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [178]:
#5)
a=np.arange(10,91,10).reshape(3,3)
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [185]:
#5) a) extract only 3rd column

print(a[:,[2]])

[[30]
 [60]
 [90]]


In [186]:
#5) b) extract only 2nd row
print(a[[1]])

[[40 50 60]]


In [208]:
#5) c)
print(a[0:2,0:2])

[[10 20]
 [40 50]]
